language: scala
# Keep in sync by hand with build.sbt.
scala:
  - 2.11.7
jdk:
  - openjdk7
sudo: false
# Caching setup from:
# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
cache:
  directories:
    - $HOME/.sbt/boot
    - $HOME/.ivy2/cache
install:
  - travis_retry ++$TRAVIS_SCALA_VERSION update
script:
  # Default Travis script.
  - sbt ++$TRAVIS_SCALA_VERSION test

  # Tricks to avoid unnecessary cache updates, also from
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
